name: MyJoin
version: 1.0.0
api:
  - 3.0.0
  - 4.0.0
author: Pytrox
main: MadTimes\MyJoin\Main
permissions:
  myjoin.myjoin:
    default: op
    description: "Permission to get the join message"
    alias: []
